version: '3'
services:
    nextjs-web:
        networks:
            - dev-vn-networks
        container_name: nextjs-web
        restart: always
        image: nextjs-web-img:1.0.0
        labels:
            - "traefik.enable=false"
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M 
    nextjs-web-nginx:
        networks:
            - dev-vn-networks
        ports:
            - "8297:80"
        container_name: nextjs-web-nginx
        restart: always
        image: nginx:latest
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - nextjs-web
        labels:
            - "traefik.docker.network=dev-vn-networks"
            - "traefik.enable=true"
            - "traefik.basic.frontend.rule=Host:nextjs-web.com"
            - "traefik.basic.port=80"
            - "traefik.basic.protocol=http"
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M 
networks:
  dev-vn-networks:
    external: true

